### ISSUE TITLE
in list() & in table() marked as wrong by parser

### ISSUE THREAD

**Issue by Zediwan** [eonum/mcl-editor#36]
<img width="618" alt="image" src="https://github.com/eonum/mcl-editor/assets/107117424/5e4d4b85-37cb-4c1f-8c9d-90113e5d112c">

**Comment by andrinM** [comment]
There is no issue. You get an error because you did not entered a value inside the braces.
in table requires a valid table label (from tables.json) and in list requires a vaild code.

**Comment by Zediwan** [comment]
Okay thanks, then the error markings need to be updated here.
