### ISSUE TITLE
Clear up usages of JSON files and use the main ones

### ISSUE THREAD

**Issue by Zediwan** [eonum/mcl-editor#4]
Is this the file stated in mylang.js ( varFilePath = 'variable_and_tables_info/variables.json') ?

_Originally posted by @jbessi in https://github.com/eonum/mcl-editor/pull/1#discussion_r1182683481_

**Comment by Zediwan** [comment]
Done for the Code Editor, yet to be for the Parser

**Comment by andrinM** [comment]
We can leave it in the Monaco folder.
