### ISSUE TITLE
Reccomendations inside of method calls like inTable()

### ISSUE THREAD

**Issue by Zediwan** [eonum/mcl-editor#7]
The idea is that when inside the brackets that there should be suggestions with all the options (variables, tables, etc)

**Comment by Zediwan** [comment]
Two things I noticed:
- If using auto completion for function, f.e. in list(), the pointer should be inside the brackets and not at the end. 
- Tables shouldn't be allowed for auto completion in "in list()" function, i.e. it's not allowed to have something like "diagnoses in list(B67_1)"  where B67_1 denotes a table.

_Originally posted by @jbessi in https://github.com/eonum/mcl-editor/pull/1#discussion_r1195047070_

**Comment by DavidRichardGit** [comment]
fixed
